### ISSUE TITLE
HTML parsing block (url-encoding tags)

### ISSUE THREAD

**Issue by wmnnd** [pragdave/earmark#390] opened 2020-10-08 03:04 UTC
Hi there, after upgrading from `1.4.1` to `1.4.10`, one of my tests started failing. Earmark now seems to have a problem parsing an empty HTML tag.
It seems like the bug was introduced in Earmark `1.4.4`; `1.4.3` doesn’t exhibit this behavior.

`<a href="https://example.org/html-link"></a>` was previously correctly parsed (i.e. left untouched).
Now `Earmark.as_html` changes it to `<a href="https://example.org/html-link%22%3E%3C/a%3E`.

**Comment by RobertDober** [comment] 2020-10-08 07:23
Thank you for reporting this, very nice to track down the exact version, which might indeed be very helpful.

That said I cannot reproduce the bug, probably I missunderstood something in the description

```iex
iex(6)> md
"<a href=\"https://example.org/html-link\"></a>"
iex(7)> Earmark.as_html(md)
{:ok, "<a href=\"https://example.org/html-link\"></a>", []}
```

Am I missing some context here?

**Comment by wmnnd** [comment] 2020-10-08 10:02
Here is the behavior in 1.4.5:

```
iex(1)>       url = "https://example.org/html-link"
"https://example.org/html-link"
iex(2)>       md = """
...(2)>       Foo2 <a href="#{url}"></a>
...(2)>       """
"Foo2 <a href=\"https://example.org/html-link\"></a>\n"
iex(3)>       Earmark.as_html!(md)
"<p>\n  Foo2 &lt;a href=”\n  <a href=\"https://example.org/html-link%22%3E%3C/a%3E\">\n    https://example.org/html-link”&gt;&lt;/a&gt;\n  </a>\n</p>\n"
```

Here is the same code in 1.4.4:
```
iex(1)>       url = "https://example.org/html-link"
"https://example.org/html-link"
iex(2)>       md = """
...(2)>       Foo2 <a href="#{url}"></a>
...(2)>       """
"Foo2 <a href=\"https://example.org/html-link\"></a>\n"
iex(3)>       Earmark.as_html!(md)
"<p>Foo2 <a href=\"https://example.org/html-link\"></a></p>\n"
```

**Comment by RobertDober** [comment] 2020-10-08 14:01
Oh I see now, thank you for your troubles.

Actually this is not a bug, HTML is not recognized unless in its own line, the implementation was too lenient < 1.4.5

I apologise for the earlier lazy implementation, but I am afraid there is not much I can do now w/o introducing a regression against the spec (while the _regression_ you experienced was more of a fix).

I completely understand that this is unexpected and even bothersome, but I am afraid there is nothing I can do.

**Comment by wmnnd** [comment] 2020-10-08 14:52
Thanks for looking into this!

But are you sure the spec requires a new line for *all* HTML elements?

John Gruber’s spec specifically says *only* block-level elements require a new line.
> For any markup that is not covered by Markdown’s syntax, you simply use HTML itself. There’s no need to preface it or delimit it to indicate that you’re switching from Markdown to HTML; you just use the tags.
> 
> The only restrictions are that block-level HTML elements — e.g. `<div>`, `<table>`, `<pre>`, `<p>`, etc. — must be separated from surrounding content by blank lines, and the start and end tags of the block should not be indented with tabs or spaces. Markdown is smart enough not to add extra (unwanted) `<p>` tags around HTML block-level tags.

– https://daringfireball.net/projects/markdown/syntax#html

And Github has an example that is almost identical to mine in their spec for GFM:
> `Foo <responsive-image src="foo.jpg" />` is parsed as `<p>Foo <responsive-image src="foo.jpg" /></p>`

– https://github.github.com/gfm/#example-636

**Comment by RobertDober** [comment] 2020-10-08 18:44
Firstly you are correct and secondly you are 100% correct...
Such bad wording from YHS. I should have written _docs_ instead of _specs_

https://github.com/pragdave/earmark#html-blocks

This means that I consider the docs as specs, however it is a moving target and I intend to define how earmark parses HTML in 1.5 please keep updated on that.

IIANM this behavior is pretty much what you want, https://github.com/RobertDober/earmark_parser/issues/7 correct?

If so I will close this as a doubleton.

**Comment by wmnnd** [comment] 2020-10-08 19:52
Thanks for the clarification. I will stick with.1.4.4 until this has been resolved :+1:

**Closed** 2020-10-09 12:29 UTC
Labels: wontfix
