### ISSUE TITLE
[Question] What does "Illegal attributes ignored in IAL" mean?

### ISSUE THREAD

**Issue by aspett** [pragdave/earmark#141] opened 2017-04-24 08:35 UTC
I'm getting a bunch of errors when running `mix docs` on a project I'm working on:

```
apps/relay/lib/relay/registry/pipelines.ex:14: warning: Illegal attributes ["pid", "ok,"] ignored in IAL
apps/relay/lib/relay/registry/locations.ex:14: warning: Illegal attributes ["pid", "ok,"] ignored in IAL
apps/relay/lib/relay/location_service/irc/supervisor.ex:14: warning: Illegal attributes ["pid", "ok,"] ignored in IAL
apps/relay/lib/relay/dispatch.ex:14: warning: Illegal attributes ["pid", "ok,"] ignored in IAL
apps/relay/lib/relay/registry/locations.ex:14: warning: Illegal attributes ["pid", "ok,"] ignored in IAL
apps/relay/lib/relay/dispatch.ex:14: warning: Illegal attributes ["pid", "ok,"] ignored in IAL
apps/relay/lib/relay/registry/locations.ex:14: warning: Illegal attributes ["pid", "ok,"] ignored in IAL
apps/relay/lib/relay/dispatch.ex:14: warning: Illegal attributes ["pid", "ok,"] ignored in IAL
apps/relay/lib/relay/registry/locations.ex:14: warning: Illegal attributes ["pid", "ok,"] ignored in IAL
apps/relay/lib/relay/dispatch.ex:14: warning: Illegal attributes ["pid", "ok,"] ignored in IAL
```

But I'm not sure what the cause of this issue is. It seems to be occurring from this package. Any tips appreciated

**Comment by aspett** [comment] 2017-04-24 08:36
A sample typespec I think might be related is:

`@spec start_link() :: { :ok, pid }`

**Comment by RobertDober** [comment] 2017-04-24 08:52
Thank you for reporting this, however the string that you are suspecting is not per se responsible for this
```
iex(1)> Earmark.as_html "@spec start_link() :: { :ok, pid }"
{:ok, "<p>@spec start_link() :: { :ok, pid }</p>\n", []}
```
If your project is public I'd gladly have a look, are you (is ex_doc) using v1.2 of Earmark?

**Comment by aspett** [comment] 2017-04-24 08:58
Hi Robert, thanks for getting back so quick! Sure, the repo is https://github.com/aspett/slackirx_new
A couple of the files appearing in those warnings, here: https://github.com/aspett/slackirx_new/blob/master/apps/relay/lib/relay/location_service/irc/supervisor.ex
and
https://github.com/aspett/slackirx_new/blob/master/apps/relay/lib/relay/dispatch.ex

Yes, I'm using ex_doc 0.14 (with earmark 1.2)

**Comment by RobertDober** [comment] 2017-04-24 09:33
Hmm seems like `ex_doc` splits the line here, because
```
iex(8)> Earmark.as_html "@spec start_link()::\n{:ok, pid}"
{:error, "<p>@spec start_link()::</p>\n",
 [{:warning, 2, "Illegal attributes [\"pid\", \"ok,\"] ignored in IAL"}]}
```

I am sorry but this will take some time and right now I do not even have a workaround for you. 

If I am guessing correctly the noise to stderr is not even your biggest problem `{:ok, pid}` should be missing
from your generated docs.

**Comment by aspett** [comment] 2017-04-24 09:44
Interesting! Oddly, I'm not seeing any missing return types so far. I phrased the issue as a question, as I noticed the warnings didn't seem to be having an effect on the general output- so wasn't sure why the warnings were appearing.

No stress, it is not a significant issue right now :). Thank you for looking into it

**Comment by RobertDober** [comment] 2017-04-24 12:36
I'll need some time with this, glad that the impact is minor.

**Comment by russmatney** [comment] 2017-05-19 22:12
@RobertDober following up - any headway or maybe starting direction/recommendation on a PR for this? Agree the issue is minor, though it's throwing for quite a few warnings for my project.

**Comment by RobertDober** [comment] 2017-05-20 08:28
@russmatney I believe that `Earmark` itself cannot do anything about it. It is passed IALs when it should not.
I did not succeed in analyzing ex_doc though. 

Whatever detailed information you could provide on this would help a lot.

This is still fantasy but I see the following possible _solutions_, assuming that it is `ex_doc` which passes an incorrect Markdown (but only incorrect in the sense that `Earmark` uses the IAL extension:

* Convince `ex_doc` ( if we are talking about `ex_doc` here) to _fix_ the input to `Earmark`. 
* Adding an IAL option which defaults to `false` to Earmark, which is really opening a Pandora's box of backward incompatibilities, but with a new version why not.

Anyway as soon if I can prove that this ex_doc I can open a dialog with them and @pragdave, and sort it out, however I would appreciate help with this as my time right now is a sparse resource ;(.

**Comment by RobertDober** [comment] 2017-05-27 10:57
Just found some time to try to reproduce this with the latest ex_doc version 0.16.1.

Seems the good folx at ex_doc have solved this already 👍 .

Can we close this issue?

**Comment by russmatney** [comment] 2017-05-27 23:36
@RobertDober Yes, it can be closed. On further investigation, looks like the warning was correct after all, as some my docstrings were indeed formatted incorrectly. Fixed that and now it runs clean. Thanks for taking a look!

**Comment by aspett** [comment] 2017-05-28 00:01
I just updated `ex_doc` to `0.16.1` in my application and ran `mix docs` again, but still get these warnings.

**Comment by aspett** [comment] 2017-05-28 00:02
@russmatney Do you have an example of the incorrect formatting?

**Comment by RobertDober** [comment] 2017-05-28 09:14
@aspett Are we still talking about slackirx_new, I tried to update to ex_doc 0.16.1 but that was not a success
```
mix docs                                                                                                                  2017-05-28 11:14:04
** (ArgumentError) :version key is required in config, got: [app: nil, aliases: [], build_per_environment: true, build_scm: Mix.SCM.Path, config_path: "config/config.exs", consolidate_protocols: true, default_task: "run", deps_path: "deps", elixirc_paths: ["lib"], erlc_paths: ["src"], erlc_include_path: "include", erlc_options: [:debug_info], lockfile: "mix.lock", apps_path: "apps", build_embedded: false, start_permanent: false, deps: [{:ex_doc, "~> 0.16.1", [only: :dev, runtime: false]}], preferred_cli_env: [inch: :docs]]
    lib/mix/tasks/docs.ex:148: Mix.Tasks.Docs.fetch_version!/1
    lib/mix/tasks/docs.ex:125: Mix.Tasks.Docs.run/3
    (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:370: Code.require_file/2
```

**Comment by RobertDober** [comment] 2017-05-28 09:32
@aspett However I found a workaround for you, just add whitespace inside the accolades `@spec start_link() :: { :ok, pid }`

It is definitely not an Earmark bug though, please report it to ex_doc.

**Closed by RobertDober** 2017-05-28 09:32 UTC

**Comment by russmatney** [comment] 2017-05-28 16:53
@RobertDober the docs error you're seeing (re: `:version key`) [has been reverted](https://github.com/elixir-lang/ex_doc/commit/69be41bb0b0d54819bf2452fc44e54d9b9e95e54) on master, and is likely unrelated.

@aspett the invalid doc string was an exposed tuple: `{}`. The diff for fixing it read as follows:

```
 -  {:system, "ENVIRONMENT_VARIABLE_NAME", "default_value"}
 +  `{:system, "ENVIRONMENT_VARIABLE_NAME", "default_value"}`
```

At this point I believe the original warnings I saw were working correctly, and I mistakenly attributed it to the issue reported here, rather than correcting my own code. Sorry if I've confused or distracted!

**Comment by romenigld** [comment] 2021-06-08 20:51
I am having this warning's as well with the versions :

```elixir

      {:ex_doc, "~> 0.24.2", only: [:dev]},
      {:earmark, "~> 1.4", only: [:dev]}
```

when I run docs:

```elixir
mix docs
zsh: correct 'docs' to 'doc' [nyae]? n

Generating docs...
warning: ExDoc.Markdown.Earmark (warning) lib/assinante.ex:37 Illegal attributes ["sucesso\"", "com", "cadastrado", "Fulano", "\"Assinante", "ok,"] ignored in IAL

View "html" docs at "doc/index.html"
warning: ExDoc.Markdown.Earmark (warning) lib/assinante.ex:37 Illegal attributes ["sucesso\"", "com", "cadastrado", "Fulano", "\"Assinante", "ok,"] ignored in IAL
```

**Comment by RobertDober** [comment] 2021-06-08 21:02
I'll gladly explain if you show me `lib/assinante.ex`

**Comment by romenigld** [comment] 2021-06-09 15:58
> I'll gladly explain if you show me `lib/assinante.ex`

I installed this versions:
```
   {:ex_doc, "~> 0.24", only: :dev, runtime: false},
      {:earmark, "~> 1.3", only: [:dev]},
```
and don't warn anymore...
