### ISSUE TITLE
allow configurable timeout for parallel rendering

### ISSUE THREAD

**Issue by fivetanley** [pragdave/earmark#191] opened 2018-07-27 22:43 UTC
Sometimes, one has a large amount of markdown parsing to do and the default timeout of `Task.await` (5000ms) is not long enough to do it. It would be great to be able to [configure the timeout passed to `Task.await`](https://github.com/pragdave/earmark/blob/8de6f9186a55b3fad00295d2d25bdfe6cf4c54cb/lib/earmark.ex#L372) instead of [overriding `pmap`](https://github.com/pragdave/earmark/blob/8de6f9186a55b3fad00295d2d25bdfe6cf4c54cb/lib/earmark/options.ex#L22), which is technically private.

I would be happy to PR this given some direction and approval that this is something the project wants.

Thanks for making/maintaining Earmark! It's helped us a lot.

**Comment by RobertDober** [comment] 2018-07-29 06:54
Yes indeed that is something we want, well need, if you have hit that hard limit.

I am certainly interested in a PR, the idea would be to instrument `Task.await`with a timeout from `Earmark.Options` which should also be implemented as a CLI argument for the escript.

That said I am a little bit intrigued where you hit that limit. In the line scanner (https://github.com/pragdave/earmark/blob/master/lib/earmark/line.ex#L81) or in the HTML renderer (https://github.com/pragdave/earmark/blob/master/lib/earmark/html_renderer.ex#L16), I'd guess in the later, man (pun intended).
Nevertheless the amount of markdown you process must be impressive.

If you do not call Earmark from the command line, but as a lib,  a workaround for the time being, could be to set `Enum.map` as the mapper in `Earmark.Options`:

```elixir
iex(3)> Earmark.as_html("* a", %Earmark.Options{mapper: &Enum.map/2})
{:ok, "<ul>\n<li>a\n</li>\n</ul>\n", []}
```

Thank you for your kind words, but it is I who is thankful to work on a useful open source project with kind, bright and helpful people around, and the privilege to work with Dave Thomas.

**Comment by RobertDober** [comment] 2018-07-29 06:55
Oh sorry I missed that you were aware of the workaround, bad communication skills 😢

**Comment by RobertDober** [comment] 2018-08-04 07:39
I am afraid that my implementation of this feature, which was simple, beware of simple solutions, right :face_with_head_bandage:  ...

ran into a regression issue.

The failing test in the PR demonstrates it quite clearly
https://github.com/pragdave/earmark/pull/192/files#diff-6f64bf9186d7d3e3eb5b310ab391cf4aR12

I think you need to override `%Options{mapper:...}` after all, as it is, technically speaking _public_ and we might run into the regression above.

Unless I can find an elegant solution to this dilemma I might need to close this issue, but I'll give it some time and will definitely listen to suggestions.

@pragdave your guidence would be appreciated.

**Comment by RobertDober** [comment] 2018-08-04 08:54
here is something which might work (far from elegant though)

https://github.com/pragdave/earmark/pull/193

I feel however that it is kludgy and really would like @pragdave 's opinion on this.

**Comment by fivetanley** [comment] 2018-08-07 16:34
@RobertDober thanks for looking into this! we ended overriding the `mapper` for now, and it's good to have a maintainer's blessing on doing so if it's technically public. :)

**Comment by RobertDober** [comment] 2018-08-08 08:43
please let me know if it is enough, because `Line.scan_lines` uses `Earmark.pmap/2` with the 5000ms hardcoded timeout, I will definitely change this, but being quite busy this might need some time to be done.

So you actually hit a _bug_ that I had not even seen in the first analysis of the issue.

**Closed** 2018-08-11 19:58 UTC
Labels: bug
