### ISSUE TITLE
Space is emitted after a tag for link?

### ISSUE THREAD

**Issue by yumaikas** [pragdave/earmark#365] opened 2020-06-27 15:56 UTC
So, I'm using earmark 1.4.5, and it seems to be emitting HTML that spits out spaces the body of an anchor tag. The image below shows the affect (as well as the results of spitting out the content in question as an AST. I'm looking into a way to fix things on my end, but yeah.

![image](https://user-images.githubusercontent.com/2996785/85926380-58878580-b85c-11ea-8d18-ec59a2741ec3.png)

**Comment by RobertDober** [comment] 2020-06-27 16:47
Please paste the markdown and the incorrect html into this ticket to allow me to reproduce the problem, thx.

**Comment by RobertDober** [comment] 2020-06-27 16:50
This is a duplicate of #359

**Closed by RobertDober** 2020-06-27 16:50 UTC

**Comment by yumaikas** [comment] 2020-06-27 22:15
Ok. For now I've gone a little [Knuthy](https://www.johndcook.com/blog/2008/05/03/reusable-code-vs-re-editable-code/) and copied/rewritten the transform.ex in my own code to remove all of the extra whitespace. I'll keep an eye out for #359. Thanks!
